---
title: "sims"
output: html_document
---

```{r}
library(wingen)
library(raster)
library(vcfR)
library(viridis)
library(foreach)
library(doParallel)

library(adegenet)
library(hierfstat)
```




# system time sims
```{r}
vcf <- read.vcfR("sims/data/mod-sim_params_it-0_t-500_spp-spp_0.vcf")
geo <- read.csv("sims/data/mod-sim_params_it-0_t-500_spp-spp_0.csv")
coords <- geo[,c("x","y")]
# FLIP COORDS TO MATCH RASTER
coords$y <- -coords$y

set.seed(21)
s <- sample(nrow(coords), 200)
l <- sample(nrow(vcf@gt), 10000)
subcoords <- coords[s,]
subvcf <- vcf[l,c(1, s+1)]

# check match
all(colnames(subvcf@gt)[-1] == geo$idx[s])

```
```{r}
lyr <- read.csv("sims/data/arda_100.csv")
lyr <- raster(as.matrix(lyr))
extent(lyr) <- extent(0,100,-100,0)

plot(lyr, col = cividis(100))
plot(lyr)
points(coords)

```

```{r}

sim <- function(vcf, coords, lyr, stat, fact = 0, wdim = 10, min_n = 2, rarify = FALSE, rarify_n = 4, rarify_nit = 10, parallel = FALSE){
  
  if(parallel){
    cores <- 6
    cl <- makeCluster(cores)
    registerDoParallel(cl)
  }
  
  # Start the clock!
  ptm <- Sys.time()

  res <- window_gd(vcf, coords, lyr, stat = "pi", fact, wdim, rarify, rarify_n, rarify_nit, min_n, fun = mean, parallel)
  
  # Stop the clock
  pt <- (Sys.time() - ptm)[3]
  
  plot(res,  col = magma(100))
  
  if(parallel){
    stopCluster(cl)
  }

  return(list(pt = pt, res = res))
}

plot(lyr, col = viridis::rocket(100))
points(subcoords)
tr <- sim(subvcf, subcoords, lyr, stat = calc_pi, fact = 2, wdim = 9, min_n = 2, rarify = TRUE, rarify_n = 4, rarify_nit = 10, parallel = TRUE)

tr_k <- krig_gd(tr[["res"]], lyr)
plot(tr_k)
tr_k_mask <- mask_gd(tr_k, 4)
```
```{r, fig.width = 12, fig.height = 3}
par(mfrow =c(1,4), pty = "s")
plot(lyr, col = viridis::magma(100), main = "Carrying capacity", axes = FALSE, box = FALSE )
plot(lyr, col = viridis::magma(100), main = "Distribution of Individuals (t = 500)", axes = FALSE, box = FALSE )
points(coords$x, coords$y, pch = 16, cex = 1, col = magma(1, begin = 1), xlab = "", ylab = "")
box()
plot(tr[["res"]]$pi, col = viridis::magma(100), main = "Window pi", axes = FALSE, box = TRUE, legend = FALSE)
plot(tr_k_mask, col = viridis::magma(100), main = "Kriged and Masked pi", axes = FALSE, box = TRUE, legend = FALSE)

```

```{r}
plot(coords$x, coords$y)
```

```{r}
time_test <- function(val, var, vcf, coords, lyr, stat = "pi", fact = 2, wdim = 5, rarify = TRUE, rarify_n = 10, rarify_nit = 10, min_n = 2){
  
  # reassign argument
  assign(var, val)
  
  ptm <- Sys.time()
  gdmapr <- window_gd(vcf, coords, lyr, stat, fact, wdim, rarify, rarify_n, rarify_nit,  min_n) 
  plot(gdmapr, col = magma(100))
  
  df <- data.frame(time = (Sys.time() - ptm)[3], 
             total_count = cellStats(mask(gdmapr[[2]], gdmapr[[1]]), "sum", na.rm = TRUE), 
             ncell = ncell(aggregate(lyr, fact)), 
             wsize = wdim*wdim, 
             wprop = wdim*wdim/ncell(aggregate(lyr, fact)),
             fact = fact)
  
  return(list(df, gdmapr))
}

unlist_test <- function(res){
  df <- purrr::map_dfr(res, function(x){x[[1]]})
  r <- purrr::map(res, function(x){x[[2]]})
  return(list(df = df, raster = r))
}


plot_time_test <- function(res, stat = "all"){
  res <- unlist_test(res)$df
  if(stat == "all"){
    par(pty = "s", mfrow = c(1,5))
    plot(res$total_count, res$time, type = "b")
    plot(res$ncell, res$time, type = "b")
    plot(res$wsize, res$time, type = "b")
    plot(res$wprop, res$time, type = "b")
    plot(res$fact, res$time, type = "b")
  } else {
    par(pty = "s", mfrow = c(1,1))
    plot(res[,stat], res$time, type = "b", xlab = stat, ylab = "System Time (seconds)")
  }

}

plot_rast_test <- function(res){
  res <- unlist_test(res)$raster
  par(pty = "s", mfrow = c(2, length(res)), mar = rep(2,4), oma = rep(2,4))
  lapply(res, function(x){plot(x[[1]], axes = FALSE, box = FALSE, col = viridis::magma(100))})
  lapply(res, function(x){plot(x[[2]], axes = FALSE, box = FALSE, col = viridis::mako(100))})
}
```


```{r, fig.width = 4, fig.height = 4}
set.seed(42)

resf <- purrr::map(c(2, 4, 8, 16), time_test, "fact", subvcf, subcoords, lyr, stat = "pi", wdim = 5, rarify = TRUE, rarify_n = 10, rarify_nit = 10)

plot_time_test(resf, stat = "fact")
```

```{r, fig.width = 10, fig.height = 5}
plot_rast_test(resf)
```

```{r, fig.width = 16, fig.height = 4}
set.seed(42)

resw <- purrr::map(c(3, 5, 7, 9, 11, 13), time_test, "wdim", subvcf, subcoords, lyr, stat = "pi", rarify = TRUE, rarify_n = 10, rarify_nit = 10)

plot_time_test(resw)

```

```{r, fig.width = 10, fig.height = 4}
plot_rast_test(resw)
```

```{r, fig.width = 16, fig.height = 4}
set.seed(42)

resf <- purrr::map(c(2, 4, 8, 16), time_test, "fact", subvcf, subcoords, lyr, stat = "pi", wdim = 5, rarify = FALSE, min_n = 10)

plot_time_test(reswf)

```

```{r, fig.width = 16, fig.height = 4}
set.seed(42)

reswf <- purrr::map(c(3, 5, 7, 9, 11, 13), time_test, "wdim", subvcf, subcoords, lyr, stat = "pi", rarify = FALSE, min_n = 10)

plot_time_test(reswf)

```




```{r}
set.seed(42)

#ress <- purrr::map(c("het", "pi", "allelic.richness"), time_test, "stat", subvcf, subcoords, lyr, fact = 2, wdim = 5, rarify = TRUE, rarify_n = 10, rarify_nit = 10)
ress <- purrr::map(c("het", "pi"), time_test, "stat", subvcf, subcoords, lyr, fact = 2, wdim = 5, rarify = TRUE, rarify_n = 10, rarify_nit = 10)

```
```{r}
calc_mean_ar

genind <- vcfR::vcfR2genind(subvcf)
system.time(calc_mean_ar(subvcf[1:10000,1:10]))
system.time(calc_mean_het(subvcf[1:10000,1:10]))
system.time(calc_pi(subvcf[1:10000,1:10]))
```

```{r}
ta <- c()
th <- c()
tp <- c()

 # calc stats
for(s in c(5, 10, 20)){
  for(stat in c("pi", "het", "allelic.richness")){
    
    vcfsub <- vcf[,c(1, sample(ncol(vcf@gt)-1, s) + 1)]
  
    if(stat == "allelic.richness"){
      gen <- vcfR::vcfR2genind(vcfsub)
      Sys.time()
      calc_mean_ar(gen)
      time <- (Sys.time() - ptm)[3]
      ta <- c(ta,time)
    }
  
    if(stat == "het"){
      gen <- vcfR::is.het(vcfR::extract.gt(vcfsub), na_is_false = FALSE)
      Sys.time()
      calc_mean_het(gen)
      time <- (Sys.time() - ptm)[3]
      th <- c(th,time)
    }
  
    if(stat == "pi"){
      gen <- vcf_to_dosage(vcfsub)
      Sys.time()
      calc_pi(gen)
      time <- (Sys.time() - ptm)[3]
      tp <- c(tp, time)
     }
    }
}


```

```{r}
df <- data.frame(sample = rep(c(5,10,20),3), time = c(ta, th, tp), stat = c(rep("AR", 3), rep("He", 3), rep("pi", 3)))
#write.csv(df, "sims/ggtime_results.csv", row.names = FALSE)
ggplot()+
  geom_line(data=df, aes(x = sample, y = time, col = stat))+
  theme_bw()
```

```{r}
ta <- c()
th <- c()
tp <- c()

 # calc stats
for(s in c(1000, 10000, nrow(vcf@gt))){
  for(stat in c("pi", "het", "allelic.richness")){
    
    vcfsub <- vcf[sample(nrow(vcf@gt), s),c(1, sample(ncol(vcf@gt)-1, 10) + 1)]
  
    if(stat == "allelic.richness"){
      gen <- vcfR::vcfR2genind(vcfsub)
      Sys.time()
      calc_mean_ar(gen)
      time <- (Sys.time() - ptm)[3]
      ta <- c(ta,time)
    }
  
    if(stat == "het"){
      gen <- vcfR::is.het(vcfR::extract.gt(vcfsub), na_is_false = FALSE)
      Sys.time()
      calc_mean_het(gen)
      time <- (Sys.time() - ptm)[3]
      th <- c(th,time)
    }
  
    if(stat == "pi"){
      gen <- vcf_to_dosage(vcfsub)
      Sys.time()
      calc_pi(gen)
      time <- (Sys.time() - ptm)[3]
      tp <- c(tp, time)
     }
    }
}

```
```{r}
df <- data.frame(sample = rep( c(1000, 10000, nrow(vcf@gt)),3), time = c(ta, th, tp), stat = c(rep("AR", 3), rep("He", 3), rep("pi", 3)))
write.csv(df, "sims/ggtime_results_loci.csv", row.names = FALSE)
ggplot()+
  geom_line(data=df, aes(x = sample, y = time, col = stat))+
  theme_bw()
```
