---
title: "nlm_sims"
output: html_document
---

 
```{r}
library(wingen)
library(raster)
library(vcfR)
library(viridis)
library(foreach)
library(doParallel)
library(here)
library(ggplot2)
library(dplyr)
library(purrr)
library(NLMR)
library(adegenet)
library(hierfstat)
source("sims_nlm_functions.R")
```

# Create NLM

```{r}
yos <- raster("data/tmp_1980-2010_90x90.tif")

range01 <- function(x){(x-min(x, na.rm = TRUE))/(max(x, na.rm = TRUE)-min(x, na.rm = TRUE))}

yos <- range01(as.matrix(yos))/2
sum(yos)

plot(raster(yos), col = magma(100))
write.table(as.matrix(yos), here("sims_nlm", "data", "nlm.csv"), row.names = FALSE, col.names = FALSE, sep = ",")

```

```{r}
ls <- list()
for(i in 1:100){
  set.seed(i)
  nlm22 <- nlm_mpd(102, 102, resolution = 1, roughness = 0.5, rescale = TRUE, verbose = TRUE)
  nlm22 <- crop(nlm22, c(0,100,0,100))
  nlm22 <- nlm22^2
  ls[[i]] <- nlm22
}
rs <- stack(ls)

nlmc <- max(rs[[1:5]])
nlmc[nlmc < 0.5] <- 0
plot(nlmc, col = magma(100))

cellStats(nlmc, sum)
write.table(as.matrix(nlmc), here("sims_nlm", "data", "nlm.csv"), row.names = FALSE, col.names = FALSE, sep = ",")

write.table(as.matrix(rs[[22]]), here("sims_nlm", "data", "nlm.csv"), row.names = FALSE, col.names = FALSE, sep = ",")
```


```{r}
nlm <- read.csv(here("sims_nlm", "data", "nlm.csv"), header = FALSE)
nlm <- raster(as.matrix(nlm))
plot(nlm, col = magma(100))
```


# Example analysis
```{r}
vcf <- read.vcfR(here("sims_nlm/data/mod-sim_params_it-0_t-500_spp-spp_0.vcf"))
geo <- read.csv(here("sims_nlm/data/mod-sim_params_it-0_t-500_spp-spp_0.csv"))
coords <- geo[,c("idx","x","y")]

set.seed(42)
l <- sample(nrow(vcf@gt), 10000)
si <- sample(nrow(coords), 200)
#write.csv( data.frame(loci = l, inds = si), "samples_seed42.csv", row.names = FALSE)

subvcf <- vcf[l,c(1, si+1)]

subcoords <- coords[si,]
subcoords <- subcoords[,c("x","y")]
subcoords$y <- -subcoords$y
coords$y <- -coords$y

# check match
all(colnames(subvcf@gt)[-1] == geo$idx[si])

```

```{r,  fig.width = 6, fig.height = 6}
lyr <- read.csv("data/nlm.csv", header = FALSE)
lyr <- raster(as.matrix(lyr))
extent(lyr) <- extent(0,100,-100,0)

kde <- raster(MASS::kde2d(coords$x, coords$y, h = c(10,10), n = 100, lims = c(0,100,-100,0)))

par(mar = rep(2,4))
plot(lyr, col = viridis::magma(100), main = "Carrying Capacity", axes = FALSE, box = FALSE)
plot(kde, col = viridis::magma(100), main = "Population Density", axes = FALSE, box = FALSE)
plot(lyr, col = mako(1, begin = 0.1, alpha = 0.1), main = "Distribution of Individuals", axes = FALSE, box = FALSE, zlim = c(0.01,1), legend = FALSE)
points(coords$x, coords$y, pch = 16, cex = 1, col = mako(1, begin = 0.7, alpha = 0.4), xlab = "", ylab = "")
points(subcoords$x, subcoords$y, pch = 16, cex = 1, col = mako(1, begin = 0.2, alpha = 0.9), xlab = "", ylab = "")
legend(0,-80, 
       c("All Individuals", "Sampled Individuals"), 
       pch = c(16,16), 
       col = c(mako(1, begin = 0.7), mako(1, begin = 0.2)),
       bty = "n",
       text.col = "black",
       cex = 1.5)

```


```{r, fig.width = 6, fig.height = 6, cache = TRUE}
cores <- 6
cl <- makeCluster(cores)
registerDoParallel(cl)

tr <- sim(subvcf, subcoords, lyr, stat = "het", fact = 3, wdim = 5, rarify = FALSE, parallel = TRUE, nloci = nrow(subvcf@gt))

stopCluster(cl)

tr_k <- krig_gd(tr[["res"]], lyr, disagg_grd = 3)
tr_k_mask <- mask_gd(tr_k, 4)

par(mar = rep(0,4), oma = rep(0,4), pty = "s")
plot(lyr, col = magma(1, begin = 0.1, alpha = 0.1), axes = FALSE, box = FALSE, zlim = c(0.01,1), legend = FALSE)
plot(tr[["res"]][[1]], col = viridis::magma(100, alpha = 1.0), main = "Window Pi", axes = FALSE, box = TRUE, legend = TRUE, add = TRUE)

plot(lyr, col = magma(1, begin = 0.1, alpha = 0.1), axes = FALSE, box = FALSE, zlim = c(0.01,1), legend = FALSE)
plot(tr_k[[1]], col = viridis::magma(100), main = "Masked Pi", axes = FALSE, box = TRUE, legend = FALSE, add = TRUE)

plot(lyr, col = magma(1, begin = 0.1, alpha = 0.1), axes = FALSE, box = FALSE, zlim = c(0.01,1), legend = FALSE)
plot(tr_k_mask, col = viridis::magma(100), main = "Kriged and Masked Pi", axes = FALSE, box = TRUE, legend = FALSE, add = TRUE)

par(mar = rep(0,4), oma = rep(0,4), pty = "s")
plot(tr[["res"]]$sample_count, col = viridis::mako(100, alpha = 1.0), axes = FALSE, box = TRUE, legend = TRUE)
plot(tr_k$sample_count, col = viridis::mako(100), axes = FALSE, box = TRUE, legend = FALSE)

```

