---
title: "Empirical Example"
output: html_document
---
```{r}
library(wingen)
library(vcfR)
library(rgdal)
library(raster)
library(viridis)
library(here)

wdir <- here("paperex", "empex")
```

```{r, fig.width=5,fig.height=5}
vcf <- read.vcfR(here(wdir, "data", "populations_r20.haplotypes.filtered_m70_randomSNP.vcf"))
coords <- read.table(here(wdir, "data", "Scelop.coord"))

states <- rgdal::readOGR(here(wdir, "TIGRIS_USA", "cb_2018_us_state_5m.shp"))

conus <- states[-which(states$NAME %in% c("Alaska", "Hawaii", "Puerto Rico", "American Samoa", "Guam", "Commonwealth of the Northern Mariana Islands", "United States Virgin Islands")),]

PNW <- states[which(states$NAME %in% c("California", "Oregon", "Washington", "Nevada", "Idaho")),]
plot(PNW)
```

# Summary figure

```{r, fig.width = 8, fig.height = 5}
par(mar = rep(0,4))
plot(conus, col = "lightgray", border = "lightgray")
plot(PNW, col = mako(1, begin = 0.7), border = "white", add = TRUE)
```

```{r, fig.width = 3, fig.height = 5}
par(mar = rep(0,4))
plot(PNW, col = mako(1, begin = 0.7), border = "white", lwd = 2)
```

# Run analysis

```{r, fig.width = 5, fig.height = 5}

lyr <- coords_to_raster(coords, disagg = 4, buffer = 1)

w = 5
f = 0
preview_gd(lyr, coords, wdim = w, fact = f, min_n = 4, sample_count = FALSE)

set.seed(22)
hg <- window_gd(vcf, coords, lyr, stat = "het", wdim = w, fact = f, rarify = TRUE, rarify_n = 2, rarify_nit = 5)

set.seed(22)
pg <- window_gd(vcf, coords, lyr, stat = "pi", wdim = w, fact = f, rarify = TRUE, rarify_n = 2, rarify_nit = 5, nloci = nrow(vcf))

set.seed(22)
ag <- window_gd(vcf, coords, lyr, stat = "biallelic.richness", wdim = w, fact = f, rarify = TRUE, rarify_n = 2, rarify_nit = 5)

par(mar = rep(0,4))
plot_gd(pg, PNW)
plot_gd(ag, PNW)
plot_gd(hg, PNW)

kpg <- krig_gd(pg[[1]], lyr, disagg_grd = 4)
mpg <- mask(kpg, PNW)

kag <- krig_gd(ag[[1]], lyr, disagg_grd = 4)
mag <- mask(kag, PNW)

khg <- krig_gd(hg[[1]], lyr, disagg_grd = 4)
mhg <- mask(khg, PNW)

```


```{r, fig.width = 12, fig.height = 6}
par(mfrow = c(1,3), mar = rep(0.5,4), oma = rep(2.5,4))
plot_gd(mpg, col = magma(10), legend.width = 2,  axis.args = list(cex.axis = 1.5))

plot(PNW, add = TRUE, col = NA, border = "white")
points(coords, pch = 16, col = mako(1, begin = 0.8), cex = 1.5)

plot_gd(mag, col = magma(10), legend.width = 2,  axis.args = list(cex.axis = 1.5))
plot(PNW, add = TRUE, col = NA, border = "white")
points(coords, pch = 16, col = mako(1, begin = 0.8), cex = 1.5)

plot_gd(mhg, col = magma(10), legend.width = 2,  axis.args = list(cex.axis = 1.5))
plot(PNW, add = TRUE, col = NA, border = "white")
points(coords, pch = 16, col = mako(1, begin = 0.8), cex = 1.5)
```

```{r, fig.width = 5, fig.height = 5}

hgn <- window_gd(vcf, coords, lyr, stat = "het", wdim = w, fact = f, rarify = FALSE, min_n = 2)

pgn <- window_gd(vcf, coords, lyr, stat = "pi", wdim = w, fact = f, rarify = FALSE, min_n = 2, nloci = nrow(vcf))

agn <- window_gd(vcf, coords, lyr, stat = "biallelic.richness", wdim = w, fact = f, rarify = FALSE, min_n = 2)

par(mar = rep(0,4))
plot_gd(hgn, PNW)
plot_gd(pgn, PNW)
plot_gd(agn, PNW)


```

```{r, fig.width = 4, fig.height = 5}
par(mar = rep(0,4))
plot_count(ag)
```

```{r, fig.width = 15, fig.height = 12}
par(mfrow = c(2, 3), mar = rep(1,4), oma = rep(3,4))

plot_gd(pg, PNW, breaks = 100, legend.width = 2, axis.args = list(cex.axis = 2))
plot_gd(ag, PNW, breaks = 100, legend.width = 2, axis.args = list(cex.axis = 2))
plot_gd(hg, PNW, breaks = 100, legend.width = 2, axis.args = list(cex.axis = 2))

plot_gd(pgn, PNW, breaks = 100, legend.width = 2, axis.args = list(cex.axis = 2))
plot_gd(agn, PNW, breaks = 100, legend.width = 2, axis.args = list(cex.axis = 2))
plot_gd(hgn, PNW, breaks = 100, legend.width = 2, axis.args = list(cex.axis = 2))

get_minmax <- function(x,y){
  x <- x[[1]]
  y <- y[[1]]
  mn <- min(cellStats(x, na.rm = TRUE, min), cellStats(y, na.rm = TRUE, min))
  mx <- max(cellStats(x, na.rm = TRUE, max), cellStats(y, na.rm = TRUE, max))
  res <- c(mn, mx)
  names(res) <- c("min", "max")
  return(res)
}

par(mfrow = c(2, 3), mar = rep(1,4), oma = rep(3,4))

plot_gd(pg, PNW, breaks = 100, zlim = get_minmax(pg, pgn), legend.width = 2, axis.args = list(cex.axis = 2))
plot_gd(ag, PNW, breaks = 100, zlim = get_minmax(ag, agn), legend.width = 2, axis.args = list(cex.axis = 2))
plot_gd(hg, PNW, breaks = 100, zlim = get_minmax(hg, hgn), legend.width = 2, axis.args = list(cex.axis = 2))

plot_gd(pgn, PNW, breaks = 100, zlim = get_minmax(pg, pgn), legend.width = 2, axis.args = list(cex.axis = 2))
plot_gd(agn, PNW, breaks = 100, zlim = get_minmax(ag, agn), legend.width = 2, axis.args = list(cex.axis = 2))
plot_gd(hgn, PNW, breaks = 100, zlim = get_minmax(hg, hgn), legend.width = 2, axis.args = list(cex.axis = 2))


```

```{r, fig.width = 5, fig.height = 9}
par(mfrow = c(3, 2), mar = rep(1,4), oma = rep(2,4))
plot_gd(hg, PNW)
plot_gd(hgn, PNW)

plot_gd(pg, PNW)
plot_gd(pgn, PNW)

plot_gd(ag, PNW)
plot_gd(agn, PNW)


par(mfrow = c(3, 2), mar = rep(1,4), oma = rep(2,4))
plot_gd(hg, PNW, zlim = c(0.029, 0.085))
plot_gd(hgn, PNW, zlim = c(0.029, 0.085))

plot_gd(pg, PNW, zlim = c(135, 611))
plot_gd(pgn, PNW, zlim = c(135, 850))

plot_gd(ag, PNW, zlim = c(1.01, 1.14))
plot_gd(agn, PNW, zlim = c(1.01, 1.14))


```

```{r, fig.width=5, fig.height=5}
preview_gd(lyr, coords, wdim = w, fact = f, min_n = 4, sample_count = FALSE)

wg <- window_gd(vcf, coords, lyr, stat = "het", wdim = w, fact = f, rarify = TRUE, rarify_n = 4, rarify_nit = 5)
plot_gd(wg)
kg <- krig_gd(wg, lyr, agg_grd = 10)
mg <- mask_gd(kg, 4)

wg2 <- window_gd(vcf, coords, lyr, stat = "het", wdim = w, fact = f, rarify = FALSE, min_n = 4)
kg2 <- krig_gd(wg2, lyr, agg_grd = 10)
mg2 <- mask_gd(kg2, 4)

par(mar = rep(0,4), oma = rep(0,4))
plot_gd(mg)
points(coords, pch = 3, col = mako(1, begin = 0.8), lwd = 1.5, cex = 0.8)

plot_gd(mg2)
points(coords)
```

```{r, fig.height = 5, fig.width = 5}
pg <- window_gd(vcf, coords, lyr, stat = "pi", wdim = w, fact = f, rarify = FALSE, min_n = 2)

ag <- window_gd(vcf, coords, lyr, stat = "biallelic.richness", wdim = w, fact = f, rarify = FALSE, min_n = 2)

par(mar = rep(0,4))
plot_gd(pg, PNW)
plot_gd(ag, PNW)
```

# Test of different wdim
```{r, fig.width = 6.5, fig.height = 7.5}


cores <- 6
cl <- makeCluster(cores)
registerDoParallel(cl)

stk <- list()

i = 1

for(n in c(2, 3, 4)){
  par(mfrow = c(2, 3), mar = rep(1,4))
  for(w in c(3, 5)){
    for(f in c(4, 3, 2)){
  
      lyr <- coords_to_raster(coords, disagg = f, plot = FALSE)
  
      pg <- window_gd(vcf, 
                      coords, 
                      lyr, 
                      stat = "pi", 
                      wdim = w, 
                      fact = 0,
                      rarify = TRUE, 
                      rarify_n = n,
                      rarify_nit = 5,
                      parallel = TRUE)
      stk[[i]] <- pg
      i <- i+1
      plot_gd(pg, PNW, zlim = c(100, 700))
      
    }
  }
}


i = 1
for(n in c(2, 3, 4)){
  par(mfrow = c(2, 3), mar = rep(1,4), oma = rep(2,4))
  for(w in c(3, 5)){
    for(f in c(4, 3, 2)){
      plot_gd(stk[[i]], PNW)
      
      i <- i+1
    }
  }
}

i = 1
for(n in c(2, 3, 4)){
  par(mfrow = c(2, 3), mar = rep(0,4), oma = rep(2,4))
  for(w in c(3, 5)){
    for(f in c(4, 3, 2)){
      plot_gd(stk[[i]], PNW, zlim = c(100, 700), legend = FALSE)
      
      i <- i+1
    }
  }
}
```



