
# Run simulations
## note: geonomics automatically generates a directory of data
python3 gnxsim.py

# move data files automatically generated by Geonomics to data folder
## note this simulation runs for 10000 time steps but we only ended up using time step 1000
cp GNX_mod-sim/it-0/spp-spp_0/*1000* data

# Run time tests
Rscript time_tests/rr_time_test.R
Rscript time_tests/WGS_time_test.R
Rscript time_tests/FULL_time_test.R
Rscript time_tests/AR_time_test.R

# The rest of the analysis is carried out in the simex_notebook.Rmd
