
# Run simulations
## note: geonomics automatically generates a directory of data
python3 gnxsim.py

# move data files automatically generated by Geonomics to data folder
## note this simulation runs for 10000 time steps but we only ended up using time step 1000
cp GNX_mod-sim/it-0/spp-spp_0/*1000* data

# create datasets for running time tests
Rscript create_dataset.R

# Run time tests
Rscript simex_tests/rr_simex_test.R
Rscript simex_tests/WGS_simex_test.R
Rscript simex_tests/FULL_simex_test.R
Rscript simex_tests/AllelicRichness_simex_test.R

# The rest of the analysis is carried out in the simex_notebook.Rmd
