# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths:
      - "R/**.R"
      - .github/workflows/R-CMD-check.yaml
      - "vignettes/**.Rmd"
    branches:
      - main
  pull_request:
       paths:
        - "R/**.R"
        - .github/workflows/R-CMD-check.yaml
        - "vignettes/**.Rmd"
        
name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install Latest ggplot2
        run: Rscript -e "install.packages('ggplot2', repos='https://cloud.r-project.org/')"

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
